---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-service
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: user-service.${DOMAIN}
    http:
      paths:
      - path: /
        backend:
          serviceName: user-service
          servicePort: http