apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: user-service
        image: app:1
        env:
        - name: SENTRY_RELEASE
          value: user-service-$(VERSION)
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: user-service
